"""OpenClaw shared brain SDK.

Brain processes (CLU, TRON, FLYNN) import from this package. The
generated HTTP client lives under `brains_shared._generated.*` —
treat that subpackage as auto-managed (re-generated by
`tools/regen-sdk.sh` after every API change). Brains never import
from `_generated` directly; the public surface is the curated
modules at this level:

- ``client.BridgeClient`` — async HTTP client with Retry-After /
  Idempotency-Key wrappers
- ``eventbus.EventSubscriber`` — WebSocket subscriber with reconnect
- ``obsidian.read_page`` / ``write_page`` / ``append_to_inbox`` —
  vault helpers
- ``llm.triage`` / ``classify`` / ``reason`` / ``draft`` /
  ``summarise`` — task_class shortcuts
"""

from brains_shared.agent import (
    AgentError,
    CreatedDraft,
    Draft,
    create_draft,
    get_draft,
    list_drafts,
    update_draft,
)
from brains_shared.client import BridgeClient, BridgeClientError, idempotency_key
from brains_shared.eventbus import (
    BridgeWebSocketError,
    EventEnvelope,
    EventSubscriber,
)
from brains_shared.events import EventPublishError, PublishedEvent, publish_event

__version__ = "0.2.0"

__all__ = [
    "AgentError",
    "BridgeClient",
    "BridgeClientError",
    "BridgeWebSocketError",
    "CreatedDraft",
    "Draft",
    "EventEnvelope",
    "EventPublishError",
    "EventSubscriber",
    "PublishedEvent",
    "__version__",
    "create_draft",
    "get_draft",
    "idempotency_key",
    "list_drafts",
    "publish_event",
    "update_draft",
]
